export const GET_ARTICLE = "GET_ARTICLE"
export const QUERY_ARTICLE = "QUERY_ARTICLE"

export const FETCH_ARTICLE = "FETCH_ARTICLE"
export const ARTICLE_FETCH_FAILED = "ARTICLE_FETCH_FAILED"
export const ARTICLE_FETCH_REQUESTED = "ARTICLE_FETCH_REQUESTED"