export { Layout } from './layout'
export { Main } from './main'
export { Sidebar } from './sidebar'
export { Seo } from './seo'
export { default as Articles } from './articles'
export { Detail } from './detail'